# Generated by Django 3.2.9 on 2021-12-08 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0007_alter_item_image'),
        ('jwt_auth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='items',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='items.item'),
            preserve_default=False,
        ),
    ]
