# Generated by Django 3.2.9 on 2021-12-08 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jwt_auth', '0002_user_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='items',
        ),
    ]
