# Generated by Django 3.2.9 on 2021-12-06 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_auto_20211206_0130'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='retail_price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=9),
            preserve_default=False,
        ),
    ]
