# Generated by Django 3.2.9 on 2021-12-07 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_item_retail_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='image',
        ),
    ]
