# Generated by Django 3.2.9 on 2021-12-08 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='item',
        ),
    ]
